### ISSUE TITLE
Using Back Button after viewing lab details causes visual dimming

### ISSUE THREAD

**Issue by daniel-widrick** [derekbaker1986/polyCS#24]
When one navigates to: http://www.cs.sunyit.edu/#/labs

and clicks on a lab and then clicks on accounts or rules and then uses the back button, the displayed page is dimmed and the buttons/links can not be interacted with.

Browser: chrome 56
OS: Windows 10

**Comment by derekbaker1986** [comment]
Bug also exists on IE 11, Edge, and Windows Firefox(non-dev browser). Bug does not appear to manifest on Linux or iOS. Need to test on other platforms. Might be related to conflict between Angular and BootstrapJS. Swapping Bootstrap modal for AngularUI modal will probably resolve this. Good find @daniel-widrick

**Comment by derekbaker1986** [comment]
I temporarily resolved this issue with a hash-change event listener that removes the classes applied when the modal is created. I also realized that the back button doesn't trigger the proper message to display in the faux-terminal. I need to eliminate the use of BootstrapJS and jQuery.
